# Generated by Django 5.1.1 on 2024-09-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_code',
        ),
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.TextField(default='500000 sent'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='mode_of_payment',
            field=models.CharField(default='Mpesa', max_length=50),
        ),
    ]
