# Generated by Django 5.1.1 on 2024-09-06 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transactions_amount_remove_transactions_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='mode_of_payment',
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transactions',
            name='unique_code',
            field=models.CharField(default='AHO4N77M8M', max_length=50),
        ),
    ]
