# Generated by Django 5.1.1 on 2024-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transactions_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='image',
            field=models.ImageField(null=True, upload_to='transactions_images/'),
        ),
    ]
