# Generated by Django 5.1.1 on 2024-09-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactions_status_alter_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='unique_code',
            field=models.CharField(max_length=50),
        ),
    ]
