# Generated by Django 5.1.1 on 2024-09-18 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreements_agreement_hash'),
        ('transactions', '0009_alter_transactions_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='agreement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='agreements.agreements'),
            preserve_default=False,
        ),
    ]
