# Generated by Django 5.1.1 on 2024-09-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreements_agreement_hash'),
        ('transactions', '0011_alter_transactions_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='agreements.agreements'),
        ),
        migrations.AddConstraint(
            model_name='transactions',
            constraint=models.CheckConstraint(condition=models.Q(('agreement__isnull', True), ('agreement_id__gt', 0), _connector='OR'), name='valid_agreement_reference'),
        ),
    ]
