# Generated by Django 5.1.1 on 2024-09-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_transactions_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transactions_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
