# Generated by Django 5.1.1 on 2024-09-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_transactions_transactions_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transactions_history',
        ),
    ]
