# Generated by Django 5.1.1 on 2024-09-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_remove_transactions_transactions_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='current_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
