# Generated by Django 5.1.1 on 2024-09-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_transactions_current_hash_transactions_previous_hash_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactions',
            name='valid_agreement_reference',
        ),
    ]
