# Generated by Django 5.1.1 on 2024-09-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('contract_duration', models.PositiveSmallIntegerField()),
                ('agreed_amount', models.PositiveIntegerField()),
                ('installment_schedule', models.TextField()),
                ('penalties_interest_rate', models.PositiveIntegerField()),
                ('down_payment', models.PositiveIntegerField()),
                ('buyer_agreed', models.BooleanField(default=False)),
                ('seller_agreed', models.BooleanField(default=False)),
                ('terms_and_conditions', models.TextField(default='No terms and conditions provided.')),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('total_amount_made', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
