# Generated by Django 5.1.1 on 2024-09-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_agreements_agreement_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreements',
            name='transactions_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
