# Generated by Django 5.1.1 on 2024-09-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='is_read',
        ),
    ]
